### PR TITLE
Fix __get_binary by excluding third party licenses

### PR DESCRIPTION
**Pull request by Jheesbrough**
Add an exclusion for files containing `THIRD_PARTY` when retrieving for the driver binary

Fixing #663 
and duplicates:
#664 
#665

### CODE REVIEW

**Review by netexpoarthur — APPROVED** [review]

**Comment by broberts19** [comment]
I tested this fix and it works. Please merge it.

**Comment by jacobfelknor** [comment]
According to the `README`, the main project maintainer has put this project on hold. Are there additional maintainers who are able to complete this PR? Just checking before I fork.....

**Comment by ggkiokas** [comment]
Can you please let us know how we can have this fix in a specific version of webdriver-manager ?

**Comment by GaryPerkins** [comment]
> Can you please let us know how we can have this fix in a specific version of webdriver-manager ?

looks like a new release is available - 4.0.2

thanks all for the quick turnaround on this

**Pull request merged**
