### PR TITLE
removed deprected executable_path from readme example

### PR DESCRIPTION
**Pull request by codingbeast**

### CODE REVIEW

**Comment by rachmadaniHaryono** [comment]
note:

https://www.selenium.dev/selenium/docs/api/py/webdriver_chrome/selenium.webdriver.chrome.webdriver.html#module-selenium.webdriver.chrome.webdriver

https://www.selenium.dev/selenium/docs/api/py/webdriver_firefox/selenium.webdriver.firefox.webdriver.html#module-selenium.webdriver.firefox.webdriver

this is from selenium 4.0.0

ie, edge, opera and first section from chrome should also be updated

**Comment by aleksandr-kotlyar** [comment]
Since a lot of people will continue to use Selenium 3 for a while - I think it would be better to keep selenium 3 examples and add selenium 4 examples.

**Comment by rachmadaniHaryono** [comment]
is this good enough https://github.com/codingbeast/webdriver_manager/pull/1 ?

**Comment by aleksandr-kotlyar** [comment]
Not enough. Better to make separate examples.

A have already did the clear one. Check out. https://github.com/SergeyPirogov/webdriver_manager/pull/297

**Comment by rachmadaniHaryono** [comment]
ok i will close my pr

**Comment by aleksandr-kotlyar** [comment]
Can be closed. Updated Readme with selenium 3 & 4 examples is already at master.

**Comment by aleksandr-kotlyar** [comment]
@codingbeast  Thank you for your work and time! Already in master [3.5.3](https://pypi.org/project/webdriver-manager/3.5.3/)

**Pull request closed without merging**
