### PR TITLE
Chnages need to resolve few issues

### PR DESCRIPTION
**Pull request by krishna3008**
I have faced a few issues with Edgedriver and I found some differences in instructions and script differences between other browsers
These changes may also help with selenium 4.0

### CODE REVIEW

**Comment by krishna3008** [comment]
I have added logging .info same as in other browsers
It resolved my issue with the edge in #272

**Comment by aleksandr-kotlyar** [comment]
Good idea! To make examples for selenium 4. But people still using selenium 3 and samples for selenium 3 need to be in README too.

**Comment by aleksandr-kotlyar** [comment]
Can be closed. Updated Readme with selenium 3 & 4 examples is already at master.

**Comment by aleksandr-kotlyar** [comment]
Already in [3.5.3](https://pypi.org/project/webdriver-manager/3.5.3/)

**Pull request closed without merging**
