### PR TITLE
Use bump2version for releases

### PR DESCRIPTION
**Pull request by s-weigand**
As for [your wish](https://github.com/SergeyPirogov/webdriver_manager/pull/101#issuecomment-636278931), I added bump2version, to make releasing more automated.

Example for the current version `2.5.3`:

Running `bump2version patch` on the master branch will update the version in `setup.py` and `webdriver_manager/__init__.py`, to `2.5.4` and create a commit with commit message `Bump version: 2.5.3 → 2.5.4`. Its also creates a tag with the name `v2.5.4` and annotation `Bump version: 2.5.3 → 2.5.4`.
When you push both with `git push --follow-tags`, the github action CI/CD, will run the tests and if they pass, deploy the new version to PyPi.

**Note:**
For the automated deployment to work, you need to set the `pypi_password` secret, if you didn't do so already ([see](https://github.com/SergeyPirogov/webdriver_manager/pull/101#issue-410727074)).

### CODE REVIEW

**Comment by s-weigand** [comment]
As so often when you rely on server responses, the failed test is a random fail. 
If you rerun the test suite it should pass.

**Comment by SergeyPirogov** [comment]
@s-weigand Ok, can I use it just by creating a tag?

**Comment by s-weigand** [comment]
@SergeyPirogov I updated my original example.
`bump2version` saves the new current version in `setup.cfg`, so if you don't make a commit you would need to keep track of it yourself.
[This is what the diff of a version bump looks like](https://github.com/s-weigand/flake8-nb/commit/dc78f4ab3de8113342303bbccccca9ba69d85083).
Also IMHO having a commit **AND** a tag is nice, since it says "This tag is a snapshot of a point in the history of this branch".

**Comment by SergeyPirogov** [comment]
@s-weigand thank you

**Pull request merged**
