### PR TITLE
Latest EdgeChromium webdriver support

### PR DESCRIPTION
**Pull request by ArunaBalasubramanian**
This PR is an enhancement to the PR already raised by Antonie.
This supports latest EdgeChromium webdriver for automatic management

### CODE REVIEW

**Comment by ArunaBalasubramanian** [comment]
@SergeyPirogov  Can you review the PR please?

**Comment by SergeyPirogov** [comment]
@ArunaBalasubramanian sure, please make CI build green

**Comment by ArunaBalasubramanian** [comment]
@SergeyPirogov It the coverage that has come down after indentation changes. Not sure how to fix them. Can you take a look please?

**Comment by SergeyPirogov** [comment]
@ArunaBalasubramanian thank you

**Pull request merged**
