### PR TITLE
Add option disable progress bar by env variable

### PR DESCRIPTION
**Pull request by DAKExDUCK**

### CODE REVIEW

**Review by mouadessalim — APPROVED** [review]
It look great, thanks for contributing to #434

**Review by aleksandr-kotlyar — APPROVED** [review]

**Comment by EwoutH** [comment]
This is awesome! Would it also be possible to add a keyword to disable it just once? That would be enough for my usecase.

**Comment by nakami** [comment]
This env variable should be mentioned in the README.

**Comment by nakami** [comment]
Added PR: https://github.com/SergeyPirogov/webdriver_manager/pull/475

**Pull request merged**
