### PR TITLE
Use github action CI/CD

### PR DESCRIPTION
**Pull request by s-weigand**
While working on #100,  I saw that you wanted to implement the azure pipeline #76 as CI.
Since github actions is the new CI on the block and azure pipelines are so 2018, I implemented a workflow for github actions. 😉 

> [Windows and Ubuntu runners are hosted in Azure.](https://help.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners#ip-addresses-of-github-hosted-runners)
[GitHub uses MacStadium to host the macOS runners.](https://help.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners#cloud-hosts-for-github-hosted-runners)

What is this workflow doing:
- Run tests for python 3.6, 37 and 3.8 on ubuntu worker
- Upload coverage to codecov
- Uploads a release to PyPi when a tag is pushed and all tests pass

The passing tests can be seen [here](https://github.com/s-weigand/webdriver_manager/runs/629885156?check_suite_focus=true)

The PyPi upload uses the [new PyPi API token](https://pypi.org/help/#apitoken), which is read from the [github secrets](https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets).
See [pypa/gh-action-pypi-publish](https://github.com/pypa/gh-action-pypi-publish) for more information.

Right now the tests only run on ubuntu, but also using Windows or MacOs is [quite easy with github actions](https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on).
After [some first tests](https://github.com/s-weigand/webdriver_manager/actions/runs/91211689), some of the tests fail on Windows and MacOs, which is most likely due to the missing `xvfb` support.
Changing the tests to use the `--headless` flag might solve this.

### CODE REVIEW

**Comment by s-weigand** [comment]
Pep8 says:
> Line 22:76: E502 the backslash is redundant between brackets
But w/o the [tests fail for python3.8](https://github.com/s-weigand/webdriver_manager/runs/629834251?check_suite_focus=true)

**Comment by SergeyPirogov** [comment]
The idea was to have ability to run tests agains windows based env

**Comment by s-weigand** [comment]
Github actions has it all, Linux, Windows and MacOs.
And it can [run 20 concurrent jobs in total](https://help.github.com/en/actions/getting-started-with-github-actions/about-github-actions#usage-limits), not only 5 like travis.

**Comment by s-weigand** [comment]
If you want I can try change the tests, to use the headless flag ,so they will also run on MacOs and Win in this PR or do a separate one after merge.

**Comment by SergeyPirogov** [comment]
@s-weigand would be great

**Comment by s-weigand** [comment]
Ok took some fighting with MacOs and and a lot of fighting the Windows worker, I got it to run on Linux, Windows and MacOs. And on the way I also fixed some bugs.

**Comment by s-weigand** [comment]
I'm not sure how much you value the default PEP8, but I for myself thing the 80char line recommandation, feels like "you need to be able to fit it on a punch card".
In my projects I use [flake8](https://pypi.org/project/flake8/), add an extra linting test stage and set th line length to 100 chars. Also `flake8` gives you more valuable information like unused imports and so on.
Also I realy love to autoformat my code with [black](https://github.com/psf/black) on file save, since IMHO formatting code yourself is, as you so well stated in the readme of this project, `boring!!!`. 😄

**Comment by SergeyPirogov** [comment]
Super cool. Let’s add this bump2version

**Pull request merged**
