### PR TITLE
Cache latest version of driver

### LINKED ISSUE #48: Check for driver latest version once a day
Here is an idea.

## What?

Cache not only binary of the driver but the latest version number as well. And update this number, let's say once a day.

## Why?

How frequently drivers are updated? Not very much.
But we waste time on each test run for requesting the latest version from the internet.
Such caching can speed up testing.

### PR DESCRIPTION
**Pull request by Maratori**
Closes #48 

- Added cache for latest driver version
- It is invalidated once a day (`config.cache_expired`)

### CODE REVIEW

**Comment by Maratori** [comment]
@SergeyPirogov We need this very much to get rid of an error: `API rate limit exceeded for <IP>. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)`

**Comment by SergeyPirogov** [comment]
@Maratori There is no any tests for this. Please add

**Comment by Maratori** [comment]
@SergeyPirogov I think that existing tests cover this.

**Comment by SergeyPirogov** [comment]
@Maratori Nope

**Pull request closed without merging**
