### PR TITLE
Add correct os_type determination while on cygwin

### PR DESCRIPTION
**Pull request by wwakabobik**
- Add correct os_type determination while on cygwin
- Up-to date README.md

### CODE REVIEW

**Comment by SergeyPirogov** [comment]
@wwakabobik Thanks

**Comment by wwakabobik** [comment]
> @wwakabobik Thanks

You're welcome. Tried to make docs actual :)

**Comment by rain01** [comment]
https://github.com/SergeyPirogov/webdriver_manager/pull/575/files#diff-ba18bbaec92175d45609614ad55533eedd3f40c3902a34b3e31f6f068cbb7970R42
Shouldn't this be:
```
elif pl == "win32" or pl == "cygwin":
```

**Comment by SergeyPirogov** [comment]
@rain01 open a pr please

**Pull request merged**
