### PR TITLE
Support further customizations allowing user defined download urls and archive types (new PR after merge with upstream)

### PR DESCRIPTION
**Pull request by seidnerj**
As indicated in https://github.com/SergeyPirogov/webdriver_manager/pull/528:

I was having an issue using this on a linux arm64 (AKA aarch64), though I could install chromium driver manually and provide the path, I thought it would be nice if this could be done via web driver manager. With the commits included in this pull request one could do the following:

```
chrome_type = ChromeType.CHROMIUM
download_url_template = "{url}/chromium-chromedriver_{version}-rpt1_{os_type}.deb"
service = ChromeService(ChromeDriverManager(name='chromedriver',
                                            chrome_type=chrome_type,
                                            os_type='arm64',
                                            url='http://archive.raspberrypi.org/debian/pool/main/c/chromium-browser',
                                            download_url_template=download_url_template
                                            ).install(), log_path=os.devnull)
```

This could also be a solution for https://github.com/SergeyPirogov/webdriver_manager/issues/479.

Thanks in advance for your consideration.

### CODE REVIEW

**Comment by SergeyPirogov** [comment]
Webdriver is only responsible for driver management. It's not the scope. Thanks

**Comment by seidnerj** [comment]
I'm not sure what you mean, this PR adds support for downloading drivers from .deb archives, for certain OS types, this is the only way source to get the appropriate chromedriver. Why is this not related to driver management?

**Comment by seidnerj** [comment]
In addition this PR fixes several issues with some tests

**Comment by SergeyPirogov** [comment]
I don't like this idea.

**Comment by seidnerj** [comment]
Well, that’s something else. 

Bottom line, this provides an option to use WebDriver manager in scenarios that today are unsupported, and which people are complaining about and seeking solutions for.

If you don’t like to enable something like this, that is of course your prerogative, however illogical it may be.

One thing is certain, you’re definitely not encouraging people to contribute to your codebase.

Good luck

**Comment by SergeyPirogov** [comment]
It should be solved in other way making possible do override DriverCache

**Comment by SergeyPirogov** [comment]
@seidnerj please look at this PR https://github.com/SergeyPirogov/webdriver_manager/pull/541/files. Now you can extend FileManager and add your custom logic and then use it like
`
driver_cache = DriverCache(file_manager=MyCustomFileManager())
manager = ChromeDriverManager()
manager.driver_cache = driver_cache
`

**Pull request closed without merging**
