### PR TITLE
Fix logger

### PR DESCRIPTION
**Pull request by SergeyPirogov**

### CODE REVIEW

**Comment by cpoenaru** [comment]
Hello,
This change breaks compatibility with usages like `IEDriverManager(log_level=logging.NOTSET)`, that was being used in order to avoid crashes when starting Internet Explorer or Edge, see here: https://github.com/SergeyPirogov/webdriver_manager/issues/269

Just a heads up. 😄

**Comment by mxrch** [comment]
Hello @SergeyPirogov, is it inteded to remove the `print_first_line` argument ? How can I remove the first lines after this commit ? :)

**Comment by SergeyPirogov** [comment]
Now its always on, please descripe a reason to supress first line?

**Comment by Pavocracy** [comment]
I'm also here due to the breaking changes nature of this PR. 

Example of my use case that no longer works:
```python
service = ChromeService(
    ChromeDriverManager(
        version=webdriver_version,
        log_level=0,
        print_first_line=False,
    ).install(),
    log_path=devnull,
)
```

The reason for wanting `log_level=0` and `print_first_line=False` is to keep the console clean. I have a tight integration with what i output to the console with my scraper, and what i log or do not log. The first line of the webdriver_manager is also multiline and has new lines after it. This breaks the flow of the output i have with my scraper.

example of my console output before the breaking changes:
```
 __             __
|  |.----.-----|  |_.-----.----.----.---.-.-----.-----.----.
|  |  -__|  -__|   _|__ --|  __|   _|  _  |  _  |  -__|   _|
|__|_____|_____|____|_____|____|__| |___._|   __|_____|__|  
         Copyright (C) 2022 Pavocracy     |__|  v2.2.0      

leetscraper comes with ABSOLUTELY NO WARRANTY;
This is free software, and you are welcome to redistribute it under
certain conditions; see GPL-2.0 License for details.

Logging started! Log file: C:\git\leetscraper\src\leetscraper/leetscraper.log
27 May 2022 08:59:19 AM [INFO]: Requesting the list of leetcode.com problems to scrape
27 May 2022 08:59:24 AM [INFO]: Attempting to scrape 3 leetcode.com problems to C:\git\leetscraper\tests\unittesting
100%|███████████████████████████████████████████████████████████████████████████████| 3/3 [00:12<00:00,  4.08s/it]
27 May 2022 08:59:36 AM [INFO]: Successfully scraped 3 leetcode.com problems!
```

and here is how it looks with print_first_line and log_level removed from the class arguments:
```
 __             __
|  |.----.-----|  |_.-----.----.----.---.-.-----.-----.----.
|  |  -__|  -__|   _|__ --|  __|   _|  _  |  _  |  -__|   _|
|__|_____|_____|____|_____|____|__| |___._|   __|_____|__|
         Copyright (C) 2022 Pavocracy     |__|  v2.2.0

leetscraper comes with ABSOLUTELY NO WARRANTY;
This is free software, and you are welcome to redistribute it under
certain conditions; see GPL-2.0 License for details.

Logging started! Log file: C:\git\leetscraper\src\leetscraper/leetscraper.log
27 May 2022 09:00:49 AM [INFO]: Requesting the list of leetcode.com problems to scrape


====== WebDriver manager ======
Trying to download new driver from https://chromedriver.storage.googleapis.com/101.0.4951.41/chromedriver_win32.zip
Driver has been saved in cache [C:\Users\AdamPavey\.wdm\drivers\chromedriver\win32\101.0.4951.41]
27 May 2022 09:00:53 AM [INFO]: Attempting to scrape 3 leetcode.com problems to C:\git\leetscraper\tests\unittesting
100%|███████████████████████████████████████████████████████████████████████████████| 3/3 [00:12<00:00,  4.00s/it]
27 May 2022 09:01:05 AM [INFO]: Successfully scraped 3 leetcode.com problems!
```


not only does it change the look of the console output, but it also skips a line from my logger output somehow :(

**Pull request merged**
