### PR TITLE
Align logging usage to python logging best practices

### LINKED ISSUE #209: can't really disable logs
I have a logger class that inherits from logger python and overrides the _log() method, webdriver manager tries to use it and fails, I would like to disable logs outside of webdriver manager log method cause the current disable functionality is to disable log parameter WDM_LOG_LEVEL on a logger that it's _log method is different.

### LINKED ISSUE #210: would like to pass logger name equals to none so it will use root logger

### LINKED ISSUE #277: Prevent log-informations?
Hello - is there any way to prevent the program for outputting this log-informations like:
```
[WDM] - ====== WebDriver manager ======
[WDM] - Current google-chrome version is 96.0.4664
[WDM] - Get LATEST driver version for 96.0.4664
[WDM] - Driver [C:\Users\Polzi\.wdm\drivers\chromedriver\win32\96.0.4664.45\chromedriver.exe] found in cache
```

I tried it with (as it is described in the description):
```
import os
os.environ['WDM_PRINT_FIRST_LINE'] = 'False'  
```

But this is not working for me - i still get the outputs in the log.

### LINKED ISSUE #287: Cant silent completely the log
with `ChromeDriverManager("2.26", log_level=0, print_first_line=False).install()` I still get the log of 
```
====== WebDriver manager ======
Driver [/Users/testuser/.wdm/drivers/chromedriver/mac64/2.26/chromedriver] found in cache
```
How do I silent that log too?

### PR DESCRIPTION
**Pull request by dariopnc**
Ref: https://docs.python.org/3/howto/logging.html#configuring-logging-for-a-library

In detail:
- completely rewrote logger.py to only consider the WDM_LOG_LEVEL environment variable
- modified every call to the logging function to adapt to the new structure
- removed unused log_level parameter for Driver object init methods

Downsides:
- Lost the abilty to set a fixed formatter for our logs
- Lost the difference in logging levels between microsoft drivers and the others
- Lost backward compatibilty for direct call to Driver object and its children

These downsides can be addressed by the module user, which is now able to properly control logs

Fixes #209
Closes #210
Fixes #277 
Fixes #287

### CODE REVIEW

**Comment by dariopnc** [comment]
@aleksandr-kotlyar To merge this change should I update test cases? Should I wait for someone else to do it?

**Comment by aleksandr-kotlyar** [comment]
@dariopnc thanks for keeping your PR up to date!

I think about - how to preprare webdriver-manager users for these changes.
1. Whats breaking changes and how to make it work again? - this info can be in PR description and in CHANGELOG.md 
2. How to fully disable logs now - this info needs to be in README.md

**Comment by dariopnc** [comment]
Ok, I suppose 9f405f24 from current master is to blame for the issue... actually even current HEAD fails some tests

**Comment by aleksandr-kotlyar** [comment]
> @aleksandr-kotlyar Updated doc as suggested but now I sincerely don't know why test_utils is failing Any suggestion regarding both documentation and test is well received :)

Thank you for your work.

I fixed test utils in new PR #298. Pull the changes please to resolve conflicts.

**Comment by dariopnc** [comment]
This PR should also solve (or help solve) #277 and #287

**Comment by dariopnc** [comment]
Hi @aleksandr-kotlyar, I've seen #343 significantly modifies the logging structure. I sincerely do not understand why this PR hasn't been considered, instead on adding a new custom behavior. Can you please explain?
The desired behavior (silent all logs) could have been achieved with this PR, by just setting WDM_LOG_LEVEL='0' as documented in the README.md file

**Pull request closed without merging**
