### PR TITLE
Adding support to the DEVOPS tools

### PR DESCRIPTION
**Pull request by krishna3008**
When selenium runs from the DEVOPS it will access mostly the system path where our user configuration is not useful I made the changes if user config returns none then it will check the direct system path.
In this code change chrome version extract from the system path is added which will take irrespective of user
This in support of #193

### CODE REVIEW

**Review by krishna3008 — COMMENTED** [review]
Made the Changes only for the windows

**Comment by aleksandr-kotlyar** [comment]
> When selenium runs from the DEVOPS it will access mostly the system path where our user configuration is not useful 

@krishna3008 whats the root cause of this problem? You tell you modify somehow - how? doesn't write to registry?

> I made the changes if user config returns none then it will check the direct system path.

System path will not be always start from disk "C:\" for all the users. This may be the cause why your PR will not be merged to the lib now.

Please, keep in mind that the library is used by hundreds and thousands of users. Thats why the browser path should be calculated more universal way.
Look at the way of using registry keys to get the path of your installation (webdriver-manager is already do so). And modify your browser installation scripts to write path to registry keys (if they still not do so).

**Comment by krishna3008** [comment]
> @krishna3008 whats the root cause of this problem? You have custom configuration - how do you configure your browser installation on the machine? Your installation is not written to the registry?
> I ma using Windows. Here I tried run my python code from the Jenkins and web driver manager doesn't able to get the version of the chrome either from master or slave. I tried the direct system program file pathe and version info is being extracted.
> System path will not be always start from disk "C:" for all the users. This may be the cause why your PR will not be merged to the lib now.
> I gave C: since the chrome will be installed when it's taken for all users in the program files.
> Please, keep in mind that the library is used by hundreds and thousands of users. Thats why the browser path should be calculated more universal way.
> Look at the way of using registry keys to get the path of your installation (webdriver-manager is already do so). And modify your browser installation scripts to write path to registry keys (if they still not do so).
I have made the PR according to the issue I have faces and seen. The user suggested a process which works via Jenkins and I tried the same for version worked successfully

**Comment by aleksandr-kotlyar** [comment]
<details><summary>quote</summary>

> @aleksandr-kotlyar
> 
> > I am using Windows. Here I tried run my python code from the Jenkins and web driver manager doesn't able to get the version of the chrome either from master or slave. I tried the direct system program file pathe and version info is being extracted.
> 
> > I gave C: since the chrome will be installed when it's taken for all users in the program files.
> 
> > I have made the PR according to the issue I have faces and seen. The user suggested a process which works via Jenkins and I tried the same for version worked successfully
> 
> > Please make the changes If any other process is being used by anyone.
</details>

@krishna3008 I understand and I am trying to help through investigation the root cause of your troubles with wdm on Jenkins. I can't help without knowing what's caused your problem. So let's get more details from your case again.
- webdriver_manager already have a code which discovers browser installation for linux/macos/windows OSes and this code works pretty stable for most of wdm users.
- You try to hardcode the path to browser which should be contained in windows registry (if windows OS on your jenkins-agent) because wdm doesn't find it from registry. It's weird because as I have said before - the code should return values from registry. The empty values makes me think that there is something with Chrome browser installation on your Jenkins agent.
 
That's why I have asked you - "how did you installed Chrome on the agent"? (And still get no answer for this question) But if you/your devops just copy-pasted chrome to this path on the jenkins-agent or installed portable version - that will describe the issue.

**Comment by krishna3008** [comment]
> quote
@aleksandr-kotlyar  

Chrome is also installed in traditional way for all users. (No modifications are done while installing or after installation. All are default settings.)

I understood that WDM also work fine for all OS and browsers.
I have ran my code with WDM from the command prompt and it's working fine.

Now I want to run my code using jenkins in a part of the DEVOPS task.
Since Nodes browser will update and to avoid the download of chrome driver I used WDM(For which this is being developed)
Every time I run with Jenkins I am getting a error 
'''
ValueError: Could not get version for Chrome with this command: reg query "HKEY_CURRENT_USER\Software\Google\Chrome\BLBeacon" /v version
[2192] Failed to execute script Gen_Cov_down
'''

And I followed up these error and seen some issues raised and suggestions through which I have made PR
#193 , #164 , #168,

**Comment by aleksandr-kotlyar** [comment]
> > quote
> > @aleksandr-kotlyar
> 
> Chrome is installed in traditional way for all users. (No modifications are done while installing or after installation. All are default settings.)
> 
> I understood that WDM also work fine for all OS and browsers.
> I have ran my code with WDM from the command prompt and it's working fine.

Okay. But how Chrome browser was installed on Jenkins agent - that it had not written to the registry? May be your Jenkins admins knows the answer?

> Every time I run with Jenkins I am getting a error
> '''
> ValueError: Could not get version for Chrome with this command: reg query "HKEY_CURRENT_USER\Software\Google\Chrome\BLBeacon" /v version
> [2192] Failed to execute script Gen_Cov_down
> '''

That's good. That tells that browser was not installed the classic way on your Jenkins agents. So you need to install it properly on Jenkins or ask Jenkins admins to do it. I think we have found the cause.
 
> And I followed up these error and seen some issues raised and suggestions through which I have made PR
> Issues I have seen similar to mine #193 , #164 , #168,

Oh, that's good. That's good. Thank you!

**Comment by krishna3008** [comment]
Thanks @aleksandr-kotlyar  for the recommendations.
>Okay. But how Chrome browser was installed on Jenkins agent - that it had not written to the registry? May be your Jenkins admins knows the answer?
In agents also the browser installed in the same way as I did in master
>That's good. I think we have found the cause. That tells that browser was not installed the classic way on your Jenkins agents. And here is a solution: you need to install it properly on Jenkins or ask Jenkins admins to do it.
I didn't understand about this.
I am the Jenkins admin for my CI machines and I just using the slave connection to that slave agents via web socket.

Since you are saying classic way
Is there any link to describe it and also did you talking about any jenkins plugins?

**Comment by krishna3008** [comment]
These Changes will be modified by the other Developers which is getting effect as per 2.5.2

**Pull request closed without merging**
