### PR TITLE
Fix edge binary driver download file type

### PR DESCRIPTION
**Pull request by ArunaBalasubramanian**

### CODE REVIEW

**Comment by SergeyPirogov** [comment]
@ArunaBalasubramanian thank you for the pull request. Seems that this change brakes some tests https://travis-ci.org/SergeyPirogov/webdriver_manager/builds/596044832?utm_source=github_status&utm_medium=notification

**Comment by ArunaBalasubramanian** [comment]
> @ArunaBalasubramanian thank you for the pull request. Seems that this change breaks some tests https://travis-ci.org/SergeyPirogov/webdriver_manager/builds/596044832?utm_source=github_status&utm_medium=notification

@SergeyPirogov Noticed, I'm fixing them. I will notify you once I'm done

**Comment by ArunaBalasubramanian** [comment]
@SergeyPirogov Hey all 9 unit tests failure are due to either 'API rate limit exceeded...' or 'Bad credentials' response from the GeckoDriver API. Is there anything that you could do?

**Comment by SergeyPirogov** [comment]
@ArunaBalasubramanian yes, this is a known issue due to limitations on Github API. Firefox drivers are stored there

**Comment by SergeyPirogov** [comment]
@ArunaBalasubramanian all tests are green on the master. Thank you https://travis-ci.org/SergeyPirogov/webdriver_manager/builds/596106116?utm_source=github_status&utm_medium=notification

**Pull request merged**
