### PR TITLE
fix: stdio problem when making exe using pyinstaller with noconsole flag

### PR DESCRIPTION
**Pull request by HHongSeungWoo**

### CODE REVIEW

**Comment by SergeyPirogov** [comment]
@HHongSeungWoo what problem we are solving by this?

**Comment by HHongSeungWoo** [comment]
@SergeyPirogov 
Test OS: windows

In browser version check function, to get a version, this library uses `os.popen`.
`os.popen` uses `subprocess.popen` with `stdin=None`, and `stderr=None`.
But, If `std*` is set to `None`, `subprocess.popen` try to find `std*` from parents.
When using pyinstaller with `--no-console`, parents do not have `std*`. So, It cause freezing.

So, I replaced `os.popen` with `subprocess.popen` and set `stderr` and `stdin` to `subprocess.DVENULL`.

**Comment by rockyhuber** [comment]
Any idea how to make the console disappear? The original console is hidden, though now with these changes it opens another console. I have tried hundreds of variations to try to make it work, best I have been able to do is make the console disappear around 5s after.

`cmd = cmd_mapping[browser_type][os_name()]
version = None
with subprocess.Popen(cmd, shell=False, creationflags=0x00000008, stdout=subprocess.PIPE, stderr=subprocess.DEVNULL, stdin=subprocess.DEVNULL) as stream:
    stdout = stream.communicate()[0].decode()
    version = re.search(pattern, stdout)`

**Comment by HHongSeungWoo** [comment]
@rockyhuber i dont speak english well, but if you want hide consloe, try using `creationflags=0x08000000`

**Pull request merged**
