### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by Maratori**
Fix some typos.

### CODE REVIEW

**Comment by SergeyPirogov** [comment]
@Maratori you should open pr to master, not production

**Comment by Maratori** [comment]
@SergeyPirogov Done.
By the way, what's the reason of having v1.6 in production branch not in master?

**Comment by SergeyPirogov** [comment]
@Maratori production is a release brunch! So after merge, package will be released to pypi. I am tired to release it by my own every time

**Comment by SergeyPirogov** [comment]
But maybe it’s better to make dev branch, set it as base and keep master as release! Need to 🤔

**Pull request merged**
