### PR TITLE
base64 encode powershell commands

### PR DESCRIPTION
**Pull request by np-8**
Base64 encode the powershell commands.

- This fixes https://github.com/SergeyPirogov/webdriver_manager/issues/307
- This replaces https://github.com/SergeyPirogov/webdriver_manager/pull/308
- This PR is compatible with https://github.com/SergeyPirogov/webdriver_manager/pull/309

### CODE REVIEW

**Comment by np-8** [comment]
Hi @aleksandr-kotlyar & @SergeyPirogov ,

Could the tests be started for this PR also?

**Comment by SergeyPirogov** [comment]
@np-8 we dont have tests for Windows, so I think it will not have a lot of impact here

**Comment by aleksandr-kotlyar** [comment]
@np-8 please explain why base64 encoding needs?

**Comment by np-8** [comment]
@aleksandr-kotlyar I did some exhaustive testing and noticed that I had made misinterperetation previously in PR308. See the Issue 322.

**Comment by np-8** [comment]
Althought, have to add that I'm not completely sure if base64 encoding would help in some rare cases. See, for example https://github.com/SergeyPirogov/webdriver_manager/pull/308#issuecomment-1043087322. If I have not made a mistake there, it seems that sometimes the base64 encoding might help.

**Pull request merged**
