### PR TITLE
FIX #649: get latest version for chrome when it's not installed

### LINKED ISSUE #649: ChromeDriver.install() bug
When trying to replicate the ChromeDriver example in the documentation, I get the following error : `AttributeError: 'NoneType' object has no attribute 'split'`

To reproduce: 
```
from selenium import webdriver
from selenium.common import NoSuchElementException
from selenium.webdriver.chrome.service import Service as ChromeService
from webdriver_manager.chrome import ChromeDriverManager

driver = webdriver.Chrome(ChromeDriverManager().install())
```

Used to work but suddenly doesn't -- maybe there was some update I'm not aware of?

### PR DESCRIPTION
**Pull request by MarcBresson**
see #649

### CODE REVIEW

**Comment by anonhostpi** [comment]
I'm assuming this is designed to support remote Chrome browsers running elsewhere other than 127.0.0.1?

**Comment by veldhaenchen** [comment]
@pep8speaks can we please merge this PR?
I checked the whole file an this is not the only PEP 8 issue...

**Review by fcole90 — APPROVED** [review]
Looks good to me, great work :rocket:

**Comment by fcole90** [comment]
@SergeyPirogov Can you have a look? :blush:

**Comment by NickCrews** [comment]
This looks good to me!

**Pull request merged**
