### PR TITLE
Chromium browser support

### LINKED ISSUE #93: Chrome Alpine (Chromium)
### Problem
If use current version `webdriver_manager 2.3.0` with `Apline linux` distributions - it can't find chrome browser in path, because there is no `google-chrome` distib at `alpine` repository.

Here is the code:
```python
import logging
from webdriver_manager import utils
def test_chrome_version():
    logging.info(utils.chrome_version())
```
Here is the stacktrace:
```console
_____________________________ test_chrome_version ______________________________
src/test/test_wdm.py:16: in test_chrome_version
    logging.info(utils.chrome_version())
/usr/local/lib/python3.7/site-packages/webdriver_manager/utils.py:98: in chrome_version
    .format(cmd)
E   ValueError: Could not get version for Chrome with this command: google-chrome --version
```
Here is [Dockerfile python:3.7-alpine + chrome:3.11-alpine](https://gist.github.com/aleksandr-kotlyar/0bfb7888cbe413b8f06cfaa8066d2e3c)

### Solution
I think we need to add checker if linux uses chromium or google-chrome browser. 
I suggest two vartiants:
#### First
That we can add check if OS.ID is Alpine, we can try to extract id of distribution like here, but python-like:
```bash
$ cat /etc/os-release
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.11.3
PRETTY_NAME="Alpine Linux v3.11"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"
$ source /etc/os-release && echo "$ID"
alpine
```

#### Second
Add second try to execute `cmd='chromium --version'` if `os_name() == OSType.LINUX`:
```python
# webdriver_manager/utils.py
def chrome_version():
    pattern = r'\d+\.\d+\.\d+'
    cmd_mapping = {
        OSType.LINUX: 'google-chrome --version',
        OSType.MAC: r'/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --version',
        OSType.WIN: r'reg query "HKEY_CURRENT_USER\Software\Google\Chrome\BLBeacon" /v version'
    }

    cmd = cmd_mapping[os_name()]
    stdout = os.popen(cmd).read()
    version = re.search(pattern, stdout)
    if not version:
        if os_name() == OSType.LINUX:
            cmd = 'chromium-browser --version'
            try:
                stdout = os.popen(cmd).read()
                version = re.search(pattern, stdout)
                assert version
                return version.group(0)
            except AssertionError:
                raise ValueError('Could not get version for Chrome with this command: {}'.format(cmd))
        raise ValueError('Could not get version for Chrome with this command: {}'.format(cmd))
    return version.group(0)
```
I can make a PR, but want to discuss first, which solution is better.
@SergeyPirogov what do you think, which solution is better? Or maybe we should wait if someone can suggest the best one?

### PR DESCRIPTION
**Pull request by aleksandr-kotlyar**
Add ChromiumDriverManager
Resolves #93

### CODE REVIEW

**Comment by SergeyPirogov** [comment]
Hello! Thank you. I think will be better chromiun to extend chrome driver manager and override several methods. Not reimplement whole class and duplicate code

**Comment by aleksandr-kotlyar** [comment]
> I think will be better chromiun to extend chrome driver manager and override several methods. Not reimplement whole class and duplicate code

I had same thoughts... 😉 
I can try to do it in a few closest hours, if i will not come with a commit - i have stucked.

**Comment by aleksandr-kotlyar** [comment]
But something went wrong with opera apt installing in the Travis-CI... I think this is another issue.

**Comment by aleksandr-kotlyar** [comment]
Here is. The best i could do. 
But maybe it would be cleaner to parametrize ChromeDriverManager somehow? All it needs - three parameters for dictionary `{OSType: command}` depends on `google-chrome` or `chromium` browser.

**Comment by aleksandr-kotlyar** [comment]
We can do it like:
```python
#webdriver_manager.utils.py 


class ChromeType(object):
    GOOGLE = 'google-chrome'
    CHROMIUM = 'chromium'


def chrome_version(browser_type=ChromeType.GOOGLE):
    pattern = r'\d+\.\d+\.\d+'
    cmd_mapping = {
        ChromeType.GOOGLE: {
            OSType.LINUX: 'google-chrome --version',
            OSType.MAC: r'/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --version',
            OSType.WIN: r'reg query "HKEY_CURRENT_USER\Software\Google\Chrome\BLBeacon" /v version'
        },
        ChromeType.CHROMIUM: {
            OSType.LINUX: 'chromium --version',
            OSType.MAC: r'/Applications/Chromium.app/Contents/MacOS/Chromium --version',
            OSType.WIN: r'reg query "HKEY_CURRENT_USER\Software\Chromium\BLBeacon" /v version'
        }
    }
```

```python
#webdriver_manager.chrome.py
class ChromeDriverManager(DriverManager):
    def __init__(self, version="latest",
                 ...
                 latest_release_url="http://chromedriver.storage.googleapis.com/LATEST_RELEASE",
                 chrome_type=ChromeType.GOOGLE):
        super(ChromeDriverManager, self).__init__(path)

        self.driver = ChromeDriver(name=name,
                                   ...
                                   latest_release_url=latest_release_url,
                                   chrome_type=chrome_type)
```
@SergeyPirogov what do you think about parametrize with default `google-chrome`? I can push commit with this full solution to take a look at.

**Comment by aleksandr-kotlyar** [comment]
First #95 and #96 should be merged to stabilize the CI.

**Pull request closed without merging**
