### PR TITLE
fix chromedriver download

### PR DESCRIPTION
**Pull request by jayph88**
fix for issue https://github.com/SergeyPirogov/webdriver_manager/issues/566

### CODE REVIEW

**Review by OdedViner — APPROVED** [review]

**Comment by PoornaYaganti** [comment]
@jayph88 Please merge the PR

**Comment by Kusuma94** [comment]
@jayph88  Review and Please merge the PR

**Comment by Kusuma94** [comment]
@SergeyPirogov Could you please help in merging the PR

**Comment by Kusuma94** [comment]
Able to see one of the test failed after merging the PR for test (3.11, 4.10.0, ubuntu-latest)

FAILED tests/test_edge_driver.py::test_edge_manager_with_selenium - selenium.common.exceptions.WebDriverException: Message: unknown error: unrecognized Microsoft Edge version: Chrome/116.0.5845.140

image

**Pull request merged**
