### PR TITLE
(feat-add) Add DEBUG_LOGGING Flag to all drivers to disable debug log…

### PR DESCRIPTION
**Pull request by greysonevins**
…ging when needed resolves  SergeyPirogov/webdriver_manager#85

### CODE REVIEW

**Comment by greysonevins** [comment]
@SergeyPirogov Now you can do this

```python
from webdriver_manager.firefox import GeckoDriverManager
GeckoDriverManager(DEBUG_LOGGING=False).install()
```

**Comment by greysonevins** [comment]
@SergeyPirogov Let me know what you think, I fixed the PEP issues with spacing.

**Comment by SergeyPirogov** [comment]
I would prefer to use an approach from #106

**Comment by greysonevins** [comment]
@SergeyPirogov, okay no worries. There only about 4-5 print statements in the whole project so I wondered if a whole logging update and log level update would be too much when the user just wanted a flag.

**Comment by SergeyPirogov** [comment]
Well, if we decided to touch this part, it's a good time to make it flexible

**Comment by greysonevins** [comment]
Okay understood.

I wonder if this is approach could be used though in some ways, I wanted this bug update solved because I use this tool in a command line tool so showing logs at all interferes with my project. A simple flag makes this reusable for me rather than having to set environment variables at all each time I want to add this project.

I wondered if the person submitting the initial issue had the same thought as me.

**Comment by SergeyPirogov** [comment]
Yes, I am trying to combine these two approaches. See my comment https://github.com/SergeyPirogov/webdriver_manager/pull/106#issuecomment-627274519

**Comment by SergeyPirogov** [comment]
Fixed in #106

**Pull request closed without merging**
