### PR TITLE
Add file lock to support mutli processes usage

### PR DESCRIPTION
**Pull request by jnhyperion**
Using `filelock` can ultimately solve the `process safe` problem without specifying any os env variables.

Also, this does not conflict with `WDM_LOCAL` or `pytest-xdist` support.

### CODE REVIEW

**Comment by stuaxo** [comment]
Are there circumstances (e.g. a reboot) where the lock could be there after the app is terminated in an unexpected way?

I wonder if an option to delete an already present lock is needed ?

**Comment by jnhyperion** [comment]
No, in my understanding, the lock is in OS io level, it does not matter with the `.lock` file exists of not.

When a process holds a file lock and it's killed somehow, the OS io level lock will automatically released, it will not impact the next lock acquire.

**Comment by SergeyPirogov** [comment]
It will not work. The multiprocess issue happen because several processes tries to write into in file/folder

**Comment by jnhyperion** [comment]
@SergeyPirogov I don't understand why you're saying it will not work. Library `filelock` aims to solve the problem exactly you described "several processes tries to write into in file/folder".

**Pull request closed without merging**
