### PR TITLE
fix UNKNOWN version on Windows

### PR DESCRIPTION
**Pull request by np-8**
- See: https://github.com/SergeyPirogov/webdriver_manager/issues/307

### CODE REVIEW

**Comment by np-8** [comment]
Hi! I finally got the https://github.com/SergeyPirogov/webdriver_manager/issues/307 fixed! 

Sorry for the code formatting changes / problems. I had `black` auto-formatting on. If you use some other auto-formatter I can save the file using that.

## demo
- Note that I do not have Firefox installed (output is correct).
```

In [1]: from webdriver_manager.utils import *

In [2]: get_browser_version_from_os("google-chrome")
[WDM] - Current google-chrome version is 98.0.4758
Out[2]: '98.0.4758'

In [3]: get_browser_version_from_os("edge")
[WDM] - Current edge version is 97.0.1072
Out[3]: '97.0.1072'

In [4]: get_browser_version_from_os("firefox")
[WDM] - Could not get version for firefox with the command: powershell -ExecutionPolicy Bypass -NoLogo -NonInteractive -NoProfile -EncodedCommand JABFAHIAcgBvAHIAQQBjAHQAaQBvAG4AUAByAGUAZgBlAHIAZQBuAGMAZQA9ACcAcwBpAGwAZQBuAHQAbAB5AGMAbwBuAHQAaQBuAHUAZQAnADsAIAAkAHQAbQBwACAAPQAgACgARwBlAHQALQBJAHQAZQBtACAALQBQAGEAdABoACAAIgAkAGUAbgB2ADoAUABSAE8ARwBSAEEATQBGAEkATABFAFMAXABNAG8AegBpAGwAbABhACAARgBpAHIAZQBmAG8AeABcAGYAaQByAGUAZgBvAHgALgBlAHgAZQAiACkALgBWAGUAcgBzAGkAbwBuAEkAbgBmAG8ALgBGAGkAbABlAFYAZQByAHMAaQBvAG4AOwAgAGkAZgAgACgAJAB0AG0AcAApACAAewBlAGMAaABvACAAJAB0AG0AcAA7ACAARQB4AGkAdAA7AH0AOwAgACQAdABtAHAAIAA9ACAAKABHAGUAdAAtAEkAdABlAG0AIAAtAFAAYQB0AGgAIAAiACQAZQBuAHYAOgBQAFIATwBHAFIAQQBNAEYASQBMAEUAUwAoAHgAOAA2ACkAXABNAG8AegBpAGwAbABhACAARgBpAHIAZQBmAG8AeABcAGYAaQByAGUAZgBvAHgALgBlAHgAZQAiACkALgBWAGUAcgBzAGkAbwBuAEkAbgBmAG8ALgBGAGkAbABlAFYAZQByAHMAaQBvAG4AOwAgAGkAZgAgACgAJAB0AG0AcAApACAAewBlAGMAaABvACAAJAB0AG0AcAA7ACAARQB4AGkAdAA7AH0AOwAgACQAdABtAHAAIAA9ACAAKABHAGUAdAAtAEkAdABlAG0AIAAoAEcAZQB0AC0ASQB0AGUAbQBQAHIAbwBwAGUAcgB0AHkAIAAnAEgASwBMAE0AOgBcAFMATwBGAFQAVwBBAFIARQBcAE0AaQBjAHIAbwBzAG8AZgB0AFwAVwBpAG4AZABvAHcAcwBcAEMAdQByAHIAZQBuAHQAVgBlAHIAcwBpAG8AbgBcAEEAcABwACAAUABhAHQAaABzAFwAZgBpAHIAZQBmAG8AeAAuAGUAeABlACcAKQAuACcAKABEAGUAZgBhAHUAbAB0ACkAJwApAC4AVgBlAHIAcwBpAG8AbgBJAG4AZgBvAC4AUAByAG8AZAB1AGMAdABWAGUAcgBzAGkAbwBuADsAIABpAGYAIAAoACQAdABtAHAAKQAgAHsAZQBjAGgAbwAgACQAdABtAHAAOwAgAEUAeABpAHQAOwB9ADsAIAAkAHQAbQBwACAAPQAgAHIAZQBnACAAcQB1AGUAcgB5ACAAIgBIAEsATABNAFwAUwBPAEYAVABXAEEAUgBFAFwATQBvAHoAaQBsAGwAYQBcAE0AbwB6AGkAbABsAGEAIABGAGkAcgBlAGYAbwB4ACIAIAAvAHYAIABDAHUAcgByAGUAbgB0AFYAZQByAHMAaQBvAG4AOwAgAGkAZgAgACgAJAB0AG0AcAApACAAewBlAGMAaABvACAAJAB0AG0AcAA7ACAARQB4AGkAdAA7AH0AOwA=
[WDM] - Current firefox version is UNKNOWN
Out[4]: 'UNKNOWN'
```

### Idea
- Use the `-EncodedCommand` and base64 encoding to make the commands work in any special case; no need to think how many quotes etc. there should be, or how to escape special characters in different situations
- The `reg query` parts are replaced with Powershell equivalents.

**Comment by np-8** [comment]
This PR also adds flags `-ExecutionPolicy Bypass -NoLogo -NonInteractive -NoProfile` to the Powershell commands.

**Comment by np-8** [comment]
As addition, I tested with and without base64 encoded commands. With `google-chrome` it did not seem to matter at all if the strings are base64 encoded (works without and with it). With `edge`, it did not work without base64 encoding (so there is probably some special character that would need special escaping.). See:

### Without base64 encoding

```python
In [3]: get_browser_version_from_os("edge")
[WDM] - Could not get version for edge with the command: powershell -ExecutionPolicy Bypass -NoLogo -NonInteractive -NoProfile $ErrorActionPreference='silentlycontinue'; $tmp = (Get-Item -Path "$env:PROGRAMFILES\Microsoft\Edge\Application\msedge.exe").VersionInfo.FileVersion; if ($tmp) {echo $tmp; Exit;}; $tmp = (Get-Item -Path "$env:PROGRAMFILES(x86)\Microsoft\Edge\Application\msedge.exe").VersionInfo.FileVersion; if ($tmp) {echo $tmp; Exit;}; $tmp = (Get-ItemProperty 
-Path Registry::"HKCU\SOFTWARE\Microsoft\Edge\BLBeacon").version; if ($tmp) {echo $tmp; Exit;}; $tmp = (Get-ItemProperty -Path Registry::"HKLM\SOFTWARE\Microsoft\EdgeUpdate\Clients\{56EB18F8-8008-4CBD-B6D2-8C97FE7E9062}").version; if ($tmp) {echo $tmp; Exit;}; $tmp = (Get-Item -Path "$env:LOCALAPPDATA\Microsoft\Edge Beta\Application\msedge.exe").VersionInfo.FileVersion; if ($tmp) {echo $tmp; Exit;}; $tmp = (Get-Item -Path "$env:PROGRAMFILES\Microsoft\Edge Beta\Application\msedge.exe").VersionInfo.FileVersion; if ($tmp) {echo $tmp; Exit;}; $tmp = (Get-Item -Path "$env:PROGRAMFILES(x86)\Microsoft\Edge Beta\Application\msedge.exe").VersionInfo.FileVersion; if ($tmp) {echo $tmp; Exit;}; $tmp = (Get-ItemProperty -Path Registry::"HKCU\SOFTWARE\Microsoft\Edge Beta\BLBeacon").version; if ($tmp) {echo $tmp; Exit;}; $tmp = (Get-Item -Path "$env:LOCALAPPDATA\Microsoft\Edge Dev\Application\msedge.exe").VersionInfo.FileVersion; if ($tmp) {echo $tmp; Exit;}; $tmp = (Get-Item -Path "$env:PROGRAMFILES\Microsoft\Edge Dev\Application\msedge.exe").VersionInfo.FileVersion; if ($tmp) {echo $tmp; Exit;}; $tmp = (Get-Item -Path "$env:PROGRAMFILES(x86)\Microsoft\Edge Dev\Application\msedge.exe").VersionInfo.FileVersion; if ($tmp) {echo $tmp; Exit;}; $tmp = (Get-ItemProperty -Path Registry::"HKCU\SOFTWARE\Microsoft\Edge Dev\BLBeacon").version; if ($tmp) {echo $tmp; Exit;}; $tmp = (Get-Item -Path "$env:LOCALAPPDATA\Microsoft\Edge SxS\Application\msedge.exe").VersionInfo.FileVersion; if ($tmp) {echo $tmp; Exit;}; $tmp = (Get-ItemProperty -Path Registry::"HKCU\SOFTWARE\Microsoft\Edge SxS\BLBeacon").version; if ($tmp) {echo $tmp; Exit;}; $tmp = (Get-Item (Get-ItemProperty 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\msedge.exe').'(Default)').VersionInfo.ProductVersion; if ($tmp) {echo $tmp; Exit;}; $tmp = [System.Diagnostics.FileVersionInfo]::GetVersionInfo((Get-ItemProperty 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\msedge.exe').'(Default)').ProductVersion; if ($tmp) {echo $tmp; Exit;}; $tmp = Get-AppxPackage -Name *MicrosoftEdge.* | Foreach Version; if ($tmp) {echo $tmp; Exit;}; $tmp = (Get-ItemProperty -Path Registry::"HKLM\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\Microsoft Edge").version; if ($tmp) {echo $tmp; Exit;};
[WDM] - Current edge version is UNKNOWN
Out[3]: 'UNKNOWN'
```

### with base64 encoding:

```python
In [2]: get_browser_version_from_os("edge")
[WDM] - Current edge version is 97.0.1072
Out[2]: '97.0.1072'
```

**Comment by np-8** [comment]
I also noted that the `ignore_errors_cmd_part` in the `windows_browser_apps_to_cmd` was left unused after my changes. Do you think it should be added to the script, and if so, how?

**Comment by aleksandr-kotlyar** [comment]
@SergeyPirogov can you please approve to execute tests?

**Pull request closed without merging**
