### PR TITLE
Allow specifying browser binary path

### PR DESCRIPTION
**Pull request by sohang3112**
Fixes [Issue 645](https://github.com/SergeyPirogov/webdriver_manager/issues/645).

Add a `binary_path` option to all `DriverManager` classes to manually specify location of browser. This is useful when the browser is installed in a non-standard location.

Example test script using Chrome:
```python
from selenium import webdriver
from selenium.webdriver.chrome.service import Service as ChromeService
from selenium.webdriver.chrome.options import Options as ChromeOptions
from webdriver_manager.chrome import ChromeDriverManager

chrome_path = "/custom/path/to/chrome"

manager = ChromeDriverManager(browser_path=chrome_path)
chromedriver_path = manager.install()

options = ChromeOptions()
options.binary_location = chrome_path
driver = webdriver.Chrome(service=ChromeService(chromedriver_path), options=options)
```

### CODE REVIEW

**Comment by sohang3112** [comment]
This fixes [Issue 645](https://github.com/SergeyPirogov/webdriver_manager/issues/645).

**Comment by sohang3112** [comment]
@SergeyPirogov please review my PR. Let me know if any changes are required from my side.

**Comment by sohang3112** [comment]
@aleksandr-kotlyar Can you please review this PR?

**Comment by sohang3112** [comment]
@MarcelWilson Last merged PR seems to be in September. Maybe the repo maintainers are taking a break (hopefully temporary!)

**Comment by ndepaola** [comment]
@sohang3112 you might have more luck switching to selenium's new built-in webdriver manager (functionally equivalent to this library but less buggy in my experience) https://www.selenium.dev/documentation/selenium_manager/#automated-browser-management

switching my project to it was trivial https://github.com/chilli-axe/mpc-autofill/pull/192

**Comment by sohang3112** [comment]
> selenium's new built-in webdriver manager

@ndepaola Thanks - didn't know about this!

**Comment by sohang3112** [comment]
> selenium's new built-in webdriver manager

@ndepaola Thanks - didn't know about this!

**Comment by aleksandr-kotlyar** [comment]
@sohang3112 this idea is awesome! Thank you for your time and this PR! Sorry but I have no time to check it, can you prove it works by adding some tests please? And also prove that no regression comes with it?

**Comment by sohang3112** [comment]
@aleksandr-kotlyar Where should I put the tests - in `tests` folder or `tests_xdist`? (I didn't really understand the purpose of `test_xdist` since all 3 files in it have the same test)

> And also prove that no regression comes with it?

How should I do that??

**Comment by aleksandr-kotlyar** [comment]
> @aleksandr-kotlyar Where should I put the tests - in `tests` folder or `tests_xdist`? (I didn't really understand the purpose of `test_xdist` since all 3 files in it have the same test)
> 
> 
> 
> > And also prove that no regression comes with it?
> 
> 
> 
> How should I do that??

To /tests/ only would be enough.
All tests should pass.

**Comment by sohang3112** [comment]
Hi. I'm closing this Pull Request, as there's already a way to do what I wanted which I didn't know before:

```python
from webdriver_manager.firefox import GeckoDriverManager

from webdriver_manager.core.utils import read_version_from_cmd 
from webdriver_manager.core.os_manager import PATTERN

firefox_path = "/usr/bin/firefox-bin-custom"
version = read_version_from_cmd(f"{firefox_path} --version", PATTERN["firefox"])
driver_binary = GeckoDriverManager(version=version).install()
```

**Pull request closed without merging**
